/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_archermind_myndk_JNITest */

#ifndef _Included_com_ndk_archermind_myndk_JNITest
#define _Included_com_ndk_archermind_myndk_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_archermind_myndk_JNITest
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ndk_archermind_myndk_JNITest_getSum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
